[package]
name = "tidal-rs_playground"
version = "0.1.0"
edition = "2021"

[dependencies]
tidal-rs = { path = "../" }
eframe = "0.29"
egui = "0.29"
dotenvy_macro = "0.15"
open = "5.3"
chrono = "0.4"
serde = "1.0"
serde_json = "1.0"
log = "0.4"
env_logger = "0.11"